"""The captured-history store: format, digest, load, save, idempotent append.

Phase H1 of docs/design/living-notes-plan.md — the store exists with **no call
sites**; nothing outside tests/test_history.py imports this module. The format
is decided in docs/design/living-notes.md §3 and was ratified 2026-09-19; this
file implements that decision, it does not propose one.

Layout (under the project root)::

    .refdes/history/
      objects/<semantic-sha256>.yaml   # canonical snapshot payload
      events/<event-id>.yaml           # {kind, occurred_at, item_key, object,
                                       #  reason, successor_key?}

Two deliberate departures from the doc's sketch, both stated in the plan:

1. **Event ids are derived, not random.** ``event_id`` is ``uuid5`` over
   ``(kind, item_key, successor_key)``. A replay of the same edge regenerates
   the identical path with the identical bytes, so idempotence (§2, case five)
   is a filesystem no-op needing no index. ``occurred_at`` is excluded from
   the id and is display metadata only — never ordered, compared, or gated on.

2. **The digest covers the semantic core only.** ``semantic_digest`` hashes
   ``{history_format, type, fields, links, body}`` — the item's own declared
   fields, raw link spellings (model.py keeps raw and resolved deliberately
   separate and write-back needs raw), and the body with whitespace collapsed.
   Identity and provenance (``key``, display ``id``, ``source`` file/line) are
   *stored* in the object but excluded from the digest, for the same reasons
   ``compute_hashes`` excludes an item's own key and display id: minting an
   identity or renaming a display id is not content, and moving an item
   between files must not make it look edited.

This digest is **not** ``item.content_hash``: that one intentionally excludes
``on_change: log`` and ``ignore`` fields (model.py ``Item.on_change_for``,
docs/design/keys.md §on_change), while a task tick must be visible in history
even though it must not churn a baseline. It is also independent of
``build.HASH_FORMAT``: a hash-format bump must never make an item look edited,
and history objects migrate only by an explicit history migration that proves
semantic equivalence.

The store refuses loudly where the format is ambiguous — an unknown higher
``history_format``, a malformed event, a duplicate of the same
(kind, item_key, successor_key) edge under two ids — rather than guessing or
silently skipping. An append-only store whose corruption is invisible is worse
than no store.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import uuid
from datetime import datetime, timezone
from typing import NamedTuple

from . import seal as seal_mod

import yaml

from . import keys as keys_mod
from . import textio
from .model import Item
from .parse import yaml_safe_load

HISTORY_FORMAT = 1

HISTORY_DIR = os.path.join(".refdes", "history")
OBJECTS_DIR = os.path.join(HISTORY_DIR, "objects")
EVENTS_DIR = os.path.join(HISTORY_DIR, "events")

# The kinds §2/§3 name, plus the two H4 writers add: `legacy-seal` markers
# (plan §H4/§H5: "recorded hash only; original content was not captured") and
# the clearly dated `migrated-current` snapshot Q3 permits behind an explicit
# flag. An event of any other kind is corruption or a writer from a future
# format, and load refuses rather than guessing.
EVENT_KINDS = frozenset(
    {
        "followed",
        "followed-corrected",
        "captured",
        "revision",
        "release",
        "redaction",
        "legacy-seal",
        "migrated-current",
    }
)

# Kinds that legitimately carry no snapshot object: a legacy-seal marker
# records that a hash exists, not content (§H5's definition), and a redaction
# event must not repeat the content it just removed (§3). Their events omit
# the `object` key entirely rather than pointing at a digest that names
# nothing -- a fake digest is exactly the lie the format exists to prevent.
NO_OBJECT_KINDS = frozenset({"legacy-seal", "redaction"})

# Fixed namespace for derived event ids: uuid5(namespace, "kind\0key\0succ")
# must be identical across processes, machines, and runs, or replay (§2 case
# four) produces a second file for the same fact instead of a no-op.
_EVENT_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "refdes:history:event")

# The only shape an object digest may take: full 64-lowercase-hex, exactly
# what `digest_of`/sha256 emits and what object filenames are built from.
_OBJECT_DIGEST_RE = re.compile(r"[0-9a-f]{64}")

_OBJECT_HEADER = (
    "# Refdes captured-history object: the canonical semantic payload of an\n"
    "# item at capture time (docs/design/living-notes.md §3). The filename is\n"
    "# the sha256 of the semantic core; do not edit this file.\n"
)

_EVENT_HEADER = (
    "# Refdes captured-history event. The id is derived from\n"
    "# (kind, item_key, successor_key), so replaying the same edge is a\n"
    "# no-op. occurred_at is display metadata only: never ordered, compared,\n"
    "# or gated on.\n"
)


class HistoryError(Exception):
    """Any history-store fault: malformed record, version refusal, digest
    mismatch, or a duplicate edge. Loud by design — the store never skips a
    bad record silently."""


# --------------------------------------------------------------- digest layer


def _collapse_ws(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def semantic_payload(item: Item) -> dict[str, object]:
    """The canonical semantic core of ``item``: what the digest covers.

    Fields keep their parsed values (defaults inherited from a ``defaults:``
    block are indistinguishable from keys written on the item — the
    ``inherited_fields`` provenance flag is deliberately not part of it), so
    the same item expressed as block YAML, flow YAML, or via defaults digests
    identically. Links are the *raw* spellings (``Item.links``), never
    ``resolved_links`` — a snapshot must record what was authored, and
    resolution is rebuildable. Body whitespace is collapsed exactly as
    ``build._hash_payload`` does, so reflowing prose is not an edit.
    """
    return {
        "history_format": HISTORY_FORMAT,
        "type": item.type,
        "fields": item.fields,
        "links": item.links,
        "body": _collapse_ws(item.body),
    }


def digest_of(payload: dict[str, object]) -> str:
    """sha256 over the canonical JSON of a semantic payload.

    ``sort_keys=True`` makes declaration order irrelevant; ``default=str``
    mirrors ``build._hash_blob`` so an exotic parsed value serializes
    deterministically instead of raising. Full 64-hex digest: object filenames
    are content addresses and collision margin is free here.
    """
    blob = json.dumps(payload, sort_keys=True, default=str)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


def semantic_digest(item: Item) -> str:
    """The separately versioned history digest of ``item``. Not
    ``item.content_hash`` (see the module docstring) and unaffected by
    ``build.HASH_FORMAT``."""
    return digest_of(semantic_payload(item))


# ------------------------------------------------------------ object records


def object_payload(item: Item) -> dict[str, object]:
    """The full object-file payload: the semantic core plus identity and
    provenance, which are stored but excluded from the digest."""
    payload = dict(semantic_payload(item))
    payload["key"] = item.key
    payload["id"] = item.id
    payload["source"] = {"file": item.source_file, "line": item.source_line}
    return payload


def _format_yaml(payload: dict[str, object], header: str) -> str:
    return header + yaml.safe_dump(
        payload, sort_keys=True, default_flow_style=False, allow_unicode=True
    )


def objects_dir(root: str) -> str:
    return os.path.join(str(root), OBJECTS_DIR)


def events_dir(root: str) -> str:
    return os.path.join(str(root), EVENTS_DIR)


def _require_valid_digest(digest: object) -> str:
    """Refuse any digest that could not be an object filename's content
    address: exactly 64 lowercase hex, the shape ``sha256().hexdigest()``
    emits. An unvalidated digest handed to ``object_path`` (then
    ``os.remove``) is a path traversal in waiting; this is the one gate every
    caller passes through."""
    if not isinstance(digest, str) or _OBJECT_DIGEST_RE.fullmatch(digest) is None:
        raise HistoryError(
            f"object digest must be exactly 64 lowercase hex characters, "
            f"got {digest!r}"
        )
    return digest


def object_path(root: str, digest: str) -> str:
    _require_valid_digest(digest)
    return os.path.join(objects_dir(root), f"{digest}.yaml")


def save_object(root: str, item: Item) -> tuple[str, str]:
    """Write ``item``'s snapshot; return ``(digest, path)``.

    Content-addressed, so the write is idempotent: a second save of the same
    state finds the file already there and writes nothing. ``source`` is
    per-capture provenance, not content — two captures of one state from
    different files/lines share a digest, and the first capture's provenance
    stands. What raises is an existing file whose *semantic core* does not
    hash to the digest in its filename: a content address that doesn't
    address its content is corruption, and it is never overwritten.
    """
    digest = semantic_digest(item)
    path = object_path(root, digest)
    text = _format_yaml(object_payload(item), _OBJECT_HEADER)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fh:
            existing = yaml_safe_load(fh)
        _check_format(existing, path)
        core = {
            k: existing[k]
            for k in ("history_format", "type", "fields", "links", "body")
            if k in existing
        }
        if digest_of(core) != digest:
            raise HistoryError(
                f"history object {path} does not hash to the content address "
                "in its filename; refusing to overwrite it"
            )
        return digest, path
    os.makedirs(os.path.dirname(path), exist_ok=True)
    # Content-addressed and immutable: this file is written once and never
    # rewritten, so its bytes must be the same whoever captured it. A
    # text-mode write made them CRLF on Windows and LF on Linux for identical
    # content.
    textio.write_text(path, text)
    return digest, path


def _check_format(data: object, where: str) -> None:
    if not isinstance(data, dict):
        raise HistoryError(f"{where}: expected a YAML mapping, got {type(data).__name__}")
    raw = data.get("history_format")
    if raw is None:
        raise HistoryError(f"{where}: missing history_format")
    try:
        version = int(raw)
    except (TypeError, ValueError):
        raise HistoryError(f"{where}: history_format {raw!r} is not an integer") from None
    if version > HISTORY_FORMAT:
        raise HistoryError(
            f"{where}: history_format {version} is newer than this build's "
            f"{HISTORY_FORMAT}; refusing to guess at a future format"
        )
    if version < 1:
        raise HistoryError(f"{where}: history_format {version} is not a real version")


def load_object(root: str, digest: str) -> dict[str, object]:
    """Load one object by its semantic digest, validating format and that the
    stored payload still hashes to the filename it lives under."""
    path = object_path(root, digest)
    if not os.path.isfile(path):
        raise HistoryError(f"no history object {digest} at {path}")
    with open(path, "r", encoding="utf-8") as fh:
        data = yaml_safe_load(fh)
    _check_format(data, path)
    data = dict(data)
    core = {k: data[k] for k in ("history_format", "type", "fields", "links", "body") if k in data}
    missing = {"history_format", "type", "fields", "links", "body"} - set(core)
    if missing:
        raise HistoryError(f"{path}: missing required key(s): {', '.join(sorted(missing))}")
    if digest_of(core) != digest:
        raise HistoryError(
            f"{path}: stored payload does not hash to its filename; the object has been tampered with"
        )
    return data


# ------------------------------------------------------------- event records


def event_id(kind: str, item_key: str, successor_key: str = "") -> str:
    """The derived id of an event: uuid5 over (kind, item_key, successor_key).

    Derived, not random (plan §H1): a replay of the same edge — the old-branch
    checkout case — regenerates the identical path and is a filesystem no-op.
    ``occurred_at`` is deliberately *not* an input; it is display metadata.
    """
    if not kind:
        raise HistoryError("event id requires a kind")
    if not item_key:
        raise HistoryError("event id requires an item_key")
    name = "\0".join([kind, item_key, successor_key or ""])
    return str(uuid.uuid5(_EVENT_NAMESPACE, name))


def append_event(
    root: str,
    kind: str,
    item_key: str,
    object_digest: str,
    *,
    successor_key: str = "",
    reason: str = "",
    occurred_at: object = None,
) -> str:
    """Append one event, idempotently; return its path.

    One event per (kind, item_key, successor_key) pair, enforced by the
    derived id: re-appending the same edge writes nothing new, even with a
    different ``occurred_at`` (a replay carries the replay clock, §2). If the
    file already exists but promises a *different* snapshot, that is two
    captures of one edge disagreeing about what was captured — a loud error,
    never a silent first-write-wins.
    """
    if kind not in EVENT_KINDS:
        raise HistoryError(f"unknown history event kind {kind!r}")
    if not object_digest and kind not in NO_OBJECT_KINDS:
        raise HistoryError("an event must name the object digest it records")
    eid = event_id(kind, item_key, successor_key)
    path = os.path.join(events_dir(root), f"{eid}.yaml")
    payload: dict[str, object] = {
        "history_format": HISTORY_FORMAT,
        "id": eid,
        "kind": kind,
        "item_key": item_key,
    }
    if object_digest:
        payload["object"] = object_digest
    if successor_key:
        payload["successor_key"] = successor_key
    if reason:
        payload["reason"] = reason
    if occurred_at is not None:
        payload["occurred_at"] = occurred_at
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fh:
            existing = yaml_safe_load(fh)
        if not isinstance(existing, dict):
            raise HistoryError(f"{path}: existing event is not a YAML mapping")
        _check_format(existing, path)
        if (existing.get("object") or "") != object_digest:
            raise HistoryError(
                f"{path}: this edge was already captured against object "
                f"{existing.get('object')!r}; refusing to re-point it at {object_digest!r}"
            )
        return path
    os.makedirs(os.path.dirname(path), exist_ok=True)
    textio.write_text(path, _format_yaml(payload, _EVENT_HEADER))
    return path


def load_events(root: str) -> list[dict[str, object]]:
    """Every event in the store, sorted by derived id (never by occurred_at —
    display metadata is not an ordering).

    Loud by design: a malformed event, an unknown kind, an id that disagrees
    with its filename, or the same (kind, item_key, successor_key) edge under
    two ids (only possible if ids were ever random) each raise. A history
    store that silently skips a bad record teaches its readers to distrust it.
    """
    directory = events_dir(root)
    if not os.path.isdir(directory):
        return []
    events: list[dict[str, object]] = []
    seen: dict[tuple[str, str, str], str] = {}
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".yaml"):
            continue
        path = os.path.join(directory, name)
        with open(path, "r", encoding="utf-8") as fh:
            data = yaml_safe_load(fh)
        _check_format(data, path)
        if data.get("kind") not in EVENT_KINDS:
            raise HistoryError(f"{path}: unknown event kind {data.get('kind')!r}")
        required = ("id", "kind", "item_key")
        if data["kind"] not in NO_OBJECT_KINDS:
            required += ("object",)
        for key in required:
            if not data.get(key):
                raise HistoryError(f"{path}: missing required key {key!r}")
        stem = name[: -len(".yaml")]
        if data["id"] != stem:
            raise HistoryError(
                f"{path}: event id {data['id']!r} does not match its filename; "
                "event files are named by their derived id"
            )
        edge = (str(data["kind"]), str(data["item_key"]), str(data.get("successor_key") or ""))
        if edge in seen:
            raise HistoryError(
                f"{path}: duplicate event for edge {edge!r}, already recorded by {seen[edge]}"
            )
        seen[edge] = path
        events.append(dict(data))
    events.sort(key=lambda event: str(event["id"]))
    return events


# ------------------------------------------------------- the capture call site


class FollowCapture(NamedTuple):
    """What one capture attempt did: the announcement line (``""`` when the
    edge was already captured, so the caller prints nothing on a no-op), the
    event's path, and exactly which files this call created — so a caller
    running a batch of captures can undo its own writes when the surrounding
    transaction fails (plan §H2: the frozen edge and its event are one unit)."""

    announcement: str
    event_path: str
    created_event: bool
    created_object: "str | None"


def _follows_target_key(target: object) -> "str | None":
    """The key half of a frozen follows target (``ID@key``, or a bare
    well-formed key for an id-less tip); None for anything unresolved."""
    text = str(target)
    if "@" in text:
        return text.partition("@")[2]
    return None


def capture_followed(
    root: str,
    predecessor: Item,
    successor: Item,
    *,
    current_predecessor_keys: "set[str] | None" = None,
) -> FollowCapture:
    """Turn one resolved (predecessor, successor) pair into a `followed`
    event holding the predecessor's snapshot (plan §H2: the one function the
    capture call site adds to this store).

    The plan's five cases, in one function:

    * **Idempotence** (case five): the derived id means re-capturing the same
      edge is a filesystem no-op that announces nothing.
    * **Typo corrected** (case one): when the successor's *current* frozen
      edges no longer include a predecessor this successor was previously
      captured against, the new event is `followed-corrected`, naming the
      superseded key in `reason`. The original event is never deleted or
      rewritten. A merge — two parents both still on the successor's edge
      list — is not a correction, so `current_predecessor_keys` must be the
      successor's full current edge set, not just this pair.
    * **Old-branch replay** (case four): derived ids plus the content-addressed
      object make the replay write the identical path with the identical
      bytes. `occurred_at` is deliberately **not** written here: a wall-clock
      stamp would give one fact different bytes in two checkouts, and §2
      makes it display metadata nobody may order or gate on. The explicit
      `history capture` command (H4) is the author moment that can carry a
      clock.

    Cases two (VS Code's save refresh) and three (CI) are the caller's:
    capture rides the freeze's `write` flag, so a writable load captures and
    `--no-write` never reaches this function.
    """
    if not predecessor.key or not successor.key:
        raise HistoryError(
            "a follows: capture is addressed by surrogate key, and "
            f"{predecessor.id or '?'} or {successor.id or '?'} has none"
        )
    if current_predecessor_keys is None:
        current_predecessor_keys = {
            key
            for key in map(_follows_target_key, successor.links.get("follows", []))
            if key
        }
    superseded = sorted(
        {
            str(event["item_key"])
            for event in load_events(root)
            if event.get("successor_key") == successor.key
            and event.get("kind") in ("followed", "followed-corrected")
            and str(event["item_key"]) not in current_predecessor_keys
        }
    )
    kind = "followed-corrected" if superseded else "followed"
    reason = (
        "supersedes the followed edge from " + ", ".join(superseded)
        if superseded
        else ""
    )

    digest = semantic_digest(predecessor)
    eid = event_id(kind, predecessor.key, successor.key)
    event_path = os.path.join(events_dir(root), f"{eid}.yaml")
    if os.path.exists(event_path):
        return FollowCapture("", event_path, False, None)

    object_file = object_path(root, digest)
    object_existed = os.path.exists(object_file)
    save_object(root, predecessor)
    try:
        append_event(
            root,
            kind,
            predecessor.key,
            digest,
            successor_key=successor.key,
            reason=reason,
        )
    except Exception:
        # An object no event points at is a leak the transaction should not
        # leave behind; content-addressed, so removing it can only undo this
        # call's own write (it did not exist a moment ago).
        if not object_existed and os.path.exists(object_file):
            os.remove(object_file)
        raise

    announcement = (
        f"captured {predecessor.id or predecessor.key}: "
        f"{successor.id or successor.key} now follows it"
    )
    if superseded:
        announcement += f" (corrects {', '.join(superseded)})"
    return FollowCapture(
        announcement, event_path, True, None if object_existed else object_file
    )


# --------------------------------------------------- edited after captured (H3)


class EditedAfterCaptured(NamedTuple):
    """One item whose live semantic content no longer matches its capture
    snapshot (plan §H3: ``(item, event, captured_digest)``). The event is the
    capture it was compared against, so the report can name it."""

    item: Item
    event: dict
    captured_digest: str


# H4 gave `captured` its writer (`refdes history capture`), so it joins the
# comparison, exactly as this comment always said it would. `revision`,
# `release`, and `migrated-current` stay out until their comparison semantics
# are decided (a migrated-current snapshot deliberately matches current
# content, so letting it silence the diagnostic is a separate call).
_CAPTURE_KINDS = ("followed", "followed-corrected", "captured")


def _frozen_follows_key(target: object) -> "str | None":
    """The key half of a follows target: ``ID@key``, or a bare well-formed
    key (an id-less tip); None for a still-bare display id — an edge whose
    spelling has not settled, which cannot disprove anything."""
    text = str(target)
    if "@" in text:
        return text.partition("@")[2]
    if len(text) == keys_mod.KEY_LEN and keys_mod.malformed_key_message(text) is None:
        return text
    return None


def _superseded(event: dict, by_key: "dict[str, Item]") -> bool:
    """Whether a capture event's edge was corrected away (§2, case one).

    The event stays in the store forever — corrected, never erased — but a
    successor that no longer edges to this predecessor means the captured
    *relationship* was the typo's, not the note's, and warning about edits
    to it would resurrect a capture the author disowned. A successor that is
    gone, or whose edges are all still-bare (unsettled), cannot disprove the
    edge, so the capture stands."""
    successor_key = str(event.get("successor_key") or "")
    if not successor_key:
        return False
    successor = by_key.get(successor_key)
    if successor is None:
        return False
    resolved = [
        key
        for key in map(_frozen_follows_key, successor.links.get("follows", []))
        if key
    ]
    if not resolved:
        return False
    return str(event["item_key"]) not in resolved


def capture_index(project) -> dict:
    """item key -> ``(representative capture event, edited_after_captured)``.

    Read-only: the store is opened here and never written — under
    ``--no-write`` or otherwise. An item with several live captures (a fork
    or merge gives one event per successor) counts as edited only when its
    current digest matches *none* of them: a second capture of the current
    state is the newest snapshot saying "this is what was captured", and
    ``occurred_at`` may not order events to find "newest" (§2). The
    representative event is a matching capture, or the lowest-id live one
    when the item is edited; ids are derived, so the pick is stable.
    """
    events = load_events(str(project.root))
    captures = [e for e in events if e["kind"] in _CAPTURE_KINDS]
    if not captures:
        return {}
    by_key = {item.key: item for item in project.items.values() if item.key}
    index: dict = {}
    for key in sorted({str(e["item_key"]) for e in captures}):
        item = by_key.get(key)
        if item is None:
            continue  # the captured item is gone; nothing live to compare
        live = [
            e
            for e in captures
            if str(e["item_key"]) == key and not _superseded(e, by_key)
        ]
        if not live:
            continue
        current = semantic_digest(item)
        matches = [e for e in live if str(e["object"]) == current]
        event = matches[0] if matches else sorted(live, key=lambda e: str(e["id"]))[0]
        index[key] = (event, not matches)
    return index


def edited_after_captured(project) -> list:
    """Every live item whose current semantic digest differs from every
    capture snapshot of it (plan §H3). A diagnostic source only: it writes
    nothing, and its callers report through ``project.warn`` — never an
    error, never a failed build."""
    by_key = {item.key: item for item in project.items.values() if item.key}
    return [
        EditedAfterCaptured(by_key[key], event, str(event["object"]))
        for key, (event, edited) in sorted(capture_index(project).items())
        if edited
    ]


# ------------------------------------------------- H4: the author commands


def _utc_now() -> str:
    """The clock an explicit author moment may carry (§2): display metadata
    only, never ordered, compared, or gated on."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def capture(root: str, item: Item, *, occurred_at: object = None) -> FollowCapture:
    """One manual capture of ``item`` (``refdes history capture``, plan §H4).

    A `captured` event — the plan's "manual" event — saying "captured",
    never "final": the item stays editable, and a later edit is the same
    H3 diagnostic as any other capture. Idempotent by the derived id: one
    capture event per item, and a second run writes nothing and announces
    nothing (Q4: the line prints only when an event was actually written).
    Unlike the follows capture, this one carries a clock — H2 deliberately
    omitted ``occurred_at`` so an edge replay is byte-identical, but an
    explicit capture is a single author moment that cannot replay without
    this exact command, and §2 names it as the write that may stamp time.
    """
    if not item.key:
        raise HistoryError(
            "a capture is addressed by surrogate key, and "
            f"{item.id or '?'} has none"
        )
    digest = semantic_digest(item)
    eid = event_id("captured", item.key)
    event_path = os.path.join(events_dir(root), f"{eid}.yaml")
    if os.path.exists(event_path):
        return FollowCapture("", event_path, False, None)

    object_file = object_path(root, digest)
    object_existed = os.path.exists(object_file)
    save_object(root, item)
    try:
        append_event(
            root,
            "captured",
            item.key,
            digest,
            reason="manual capture",
            occurred_at=occurred_at if occurred_at is not None else _utc_now(),
        )
    except Exception:
        if not object_existed and os.path.exists(object_file):
            os.remove(object_file)
        raise
    return FollowCapture(
        f"captured {item.id or item.key}: manual capture",
        event_path,
        True,
        None if object_existed else object_file,
    )


class RedactionResult(NamedTuple):
    """What one ``redact`` did: the target it was addressed by, the object
    digests and event records removed, and the redaction event written
    (``None`` when nothing matched and nothing was written)."""

    target: str
    removed_objects: list
    removed_events: list
    event_path: "str | None"


def redact(
    root: str, *, item_key: str = None, object_digest: str = None
) -> RedactionResult:
    """Remove matching objects and events, then write one auditable
    ``redaction`` event (§3, plan §H4).

    The event names what was removed — object digests and event ids —
    without repeating any of its content: a digest is an address, not the
    secret. Rules the plan leaves open, resolved as stated in
    ``in-prog-logs/living-notes-phase-h4.md``:

    * Redaction events themselves are never redaction targets. Removing the
      audit trail of a prior redaction would make the second leak
      indistinguishable from no leak at all.
    * An item target removes the events *of* that item (``item_key``), not
      events that point at it as a successor — those record other items.
    * An object is deleted only when no surviving event still references it
      (content addressing lets two identical items share one snapshot).
    * The event's ``successor_key`` carries a fingerprint of the removal
      set, so a second, genuinely different redaction of the same target
      gets its own event id instead of colliding with the first.
    * A caller-supplied ``object_digest`` must be exactly 64 lowercase hex
      (``_require_valid_digest``) and is refused before the store is even
      read: an unvalidated digest reaching ``object_path``+``os.remove`` is
      a path traversal.

    Transactional: every removed file's bytes are held in memory and
    restored if any step fails, so a half-redacted store is not a state
    this function can leave behind.
    """
    if (item_key is None) == (object_digest is None):
        raise HistoryError("redact takes exactly one of item_key or object_digest")
    if object_digest is not None:
        _require_valid_digest(object_digest)  # before any filesystem access
    root = str(root)
    events = load_events(root)
    if object_digest is not None:
        doomed = [
            e
            for e in events
            if e["kind"] != "redaction" and str(e.get("object") or "") == object_digest
        ]
        digests = {object_digest}
    else:
        doomed = [
            e
            for e in events
            if e["kind"] != "redaction" and str(e["item_key"]) == item_key
        ]
        referenced = {str(e["object"]) for e in doomed if e.get("object")}
        keep = [e for e in events if e not in doomed]
        digests = {
            d
            for d in referenced
            if not any(str(e.get("object") or "") == d for e in keep)
        }
    target = item_key or object_digest
    object_exists = object_digest is not None and os.path.isfile(
        object_path(root, object_digest)
    )
    if not doomed and not object_exists:
        return RedactionResult(target, [], [], None)

    removed_files: list[tuple[str, bytes]] = []
    try:
        for event in doomed:
            path = os.path.join(events_dir(root), f"{event['id']}.yaml")
            with open(path, "rb") as fh:
                blob = fh.read()
            os.remove(path)
            removed_files.append((path, blob))
        removed_digests = []
        for digest in sorted(digests):
            path = object_path(root, digest)
            if os.path.isfile(path):
                with open(path, "rb") as fh:
                    blob = fh.read()
                os.remove(path)
                removed_files.append((path, blob))
                removed_digests.append(digest)
        fingerprint = hashlib.sha256(
            "\0".join(
                sorted(removed_digests + [str(e["id"]) for e in doomed])
            ).encode("utf-8")
        ).hexdigest()[:12]
        reason = (
            f"redacted {len(removed_digests)} object(s) and "
            f"{len(doomed)} event(s): "
            + "objects "
            + (", ".join(removed_digests) or "-")
            + "; events "
            + ", ".join(str(e["id"]) for e in doomed)
        )
        event_path = append_event(
            root,
            "redaction",
            str(target),
            "",
            successor_key=fingerprint,
            reason=reason,
        )
    except Exception:
        for path, blob in removed_files:
            with open(path, "wb") as fh:
                fh.write(blob)
        raise
    return RedactionResult(target, removed_digests, doomed, event_path)


class SealMarker(NamedTuple):
    """One legacy seal record's migration outcome (``refdes history
    migrate-seals``, plan §H4). ``current`` is the ``--capture-current``
    verdict: ``""`` (flag not given), ``"captured"``, ``"differs"`` (live
    content no longer matches the recorded hash — capturing it would dress
    up drift as migration), or ``"unresolved"`` (no live item)."""

    seal_file: str
    record_id: str
    item_key: str
    display_id: "str | None"
    marker_path: str
    marker_created: bool
    current: str
    current_path: "str | None"


def migrate_seals(project, *, capture_current: bool = False, occurred_at: object = None) -> list:
    """Read every legacy seal file and write one ``legacy-seal`` marker per
    record (§8: "do not delete legacy seal support until a migration has
    run"; the command lands in H4 so the migration is one documented
    transaction).

    A marker is "recorded hash only; original content was not captured"
    (§H5's definition): no snapshot object, and the reason names the seal
    file and the recorded hash so the marker is self-describing. The seal
    file itself is never touched. Derived ids make the migration
    idempotent; a record that appears in two files (the transitional
    base-file/board-file overlap ``seal.py`` documents) yields one marker.

    ``capture_current`` is Q3's explicit flag: for a seal record whose live
    item's content still matches its recorded hash (compared through
    ``seal._matches_sealed_hash``, the one shared hash-format migration
    reader), capture the *current* snapshot as a clearly dated
    ``migrated-current`` event — never labelled seal-time text, which is
    the specific lie §8 forbids. Callers must run ``build.compute_hashes``
    first; an item whose ``content_hash`` was never computed simply
    reports ``differs``.
    """
    root = str(project.root)
    markers = []
    for board in sorted({""} | set(project.boards)):
        path = seal_mod.seal_path(project, board)
        if not os.path.isfile(path):
            continue
        rel = os.path.relpath(path, root).replace("\\", "/")
        seals = seal_mod.load_seals(project, board)
        for record_id in sorted(seals):
            key, display_id, recorded, hash_format = seal_mod._seal_parts(
                record_id, seals[record_id]
            )
            item = project.items.get(key) if key else None
            if item is None and display_id:
                item = project.item_by_id(display_id)
            item_key = str(key or (item.key if item and item.key else display_id or record_id))
            reason = (
                f"legacy seal for {display_id or record_id} in {rel}; "
                f"recorded hash {recorded}"
                + (f" (hash_format {hash_format})" if hash_format is not None else "")
                + "; original content was not captured"
            )
            marker_path = os.path.join(
                events_dir(root), f"{event_id('legacy-seal', item_key)}.yaml"
            )
            marker_created = not os.path.exists(marker_path)
            append_event(root, "legacy-seal", item_key, "", reason=reason)

            current, current_path = "", None
            if capture_current:
                if item is None:
                    current = "unresolved"
                else:
                    matches, _hash = seal_mod._matches_sealed_hash(
                        recorded, item, project, hash_format
                    )
                    if not matches:
                        current = "differs"
                    else:
                        digest = save_object(root, item)[0]
                        current_path = append_event(
                            root,
                            "migrated-current",
                            item.key,
                            digest,
                            reason=(
                                "current content captured at seal migration; "
                                "this is not seal-time text"
                            ),
                            occurred_at=(
                                occurred_at if occurred_at is not None else _utc_now()
                            ),
                        )
                        current = "captured"
            markers.append(
                SealMarker(
                    rel, record_id, item_key, display_id,
                    marker_path, marker_created, current, current_path,
                )
            )
    return markers
