"""The captured-history store: format, digest, load, save, idempotent append.

Phase H1 of docs/design/living-notes-plan.md — the store exists with **no call
sites**; nothing outside tests/test_history.py imports this module. The format
is decided in docs/design/living-notes.md §3 and was ratified 2026-09-19; this
file implements that decision, it does not propose one.

Layout (under the project root)::

    .refdes/history/
      objects/<semantic-sha256>.yaml   # canonical snapshot payload
      events/<event-id>.yaml           # {kind, occurred_at, item_key, object,
                                       #  reason, successor_key?}

Two deliberate departures from the doc's sketch, both stated in the plan:

1. **Event ids are derived, not random.** ``event_id`` is ``uuid5`` over
   ``(kind, item_key, successor_key)``. A replay of the same edge regenerates
   the identical path with the identical bytes, so idempotence (§2, case five)
   is a filesystem no-op needing no index. ``occurred_at`` is excluded from
   the id and is display metadata only — never ordered, compared, or gated on.

2. **The digest covers the semantic core only.** ``semantic_digest`` hashes
   ``{history_format, type, fields, links, body}`` — the item's own declared
   fields, raw link spellings (model.py keeps raw and resolved deliberately
   separate and write-back needs raw), and the body with whitespace collapsed.
   Identity and provenance (``key``, display ``id``, ``source`` file/line) are
   *stored* in the object but excluded from the digest, for the same reasons
   ``compute_hashes`` excludes an item's own key and display id: minting an
   identity or renaming a display id is not content, and moving an item
   between files must not make it look edited.

This digest is **not** ``item.content_hash``: that one intentionally excludes
``on_change: log`` and ``ignore`` fields (model.py ``Item.on_change_for``,
docs/design/keys.md §on_change), while a task tick must be visible in history
even though it must not churn a baseline. It is also independent of
``build.HASH_FORMAT``: a hash-format bump must never make an item look edited,
and history objects migrate only by an explicit history migration that proves
semantic equivalence.

The store refuses loudly where the format is ambiguous — an unknown higher
``history_format``, a malformed event, a duplicate of the same
(kind, item_key, successor_key) edge under two ids — rather than guessing or
silently skipping. An append-only store whose corruption is invisible is worse
than no store.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import uuid
from typing import NamedTuple

import yaml

from .model import Item
from .parse import yaml_safe_load

HISTORY_FORMAT = 1

HISTORY_DIR = os.path.join(".refdes", "history")
OBJECTS_DIR = os.path.join(HISTORY_DIR, "objects")
EVENTS_DIR = os.path.join(HISTORY_DIR, "events")

# The kinds §2/§3 name. An event of any other kind is corruption or a writer
# from a future format, and load refuses rather than guessing.
EVENT_KINDS = frozenset(
    {
        "followed",
        "followed-corrected",
        "captured",
        "revision",
        "release",
        "redaction",
    }
)

# Fixed namespace for derived event ids: uuid5(namespace, "kind\0key\0succ")
# must be identical across processes, machines, and runs, or replay (§2 case
# four) produces a second file for the same fact instead of a no-op.
_EVENT_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "refdes:history:event")

_OBJECT_HEADER = (
    "# Refdes captured-history object: the canonical semantic payload of an\n"
    "# item at capture time (docs/design/living-notes.md §3). The filename is\n"
    "# the sha256 of the semantic core; do not edit this file.\n"
)

_EVENT_HEADER = (
    "# Refdes captured-history event. The id is derived from\n"
    "# (kind, item_key, successor_key), so replaying the same edge is a\n"
    "# no-op. occurred_at is display metadata only: never ordered, compared,\n"
    "# or gated on.\n"
)


class HistoryError(Exception):
    """Any history-store fault: malformed record, version refusal, digest
    mismatch, or a duplicate edge. Loud by design — the store never skips a
    bad record silently."""


# --------------------------------------------------------------- digest layer


def _collapse_ws(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def semantic_payload(item: Item) -> dict[str, object]:
    """The canonical semantic core of ``item``: what the digest covers.

    Fields keep their parsed values (defaults inherited from a ``defaults:``
    block are indistinguishable from keys written on the item — the
    ``inherited_fields`` provenance flag is deliberately not part of it), so
    the same item expressed as block YAML, flow YAML, or via defaults digests
    identically. Links are the *raw* spellings (``Item.links``), never
    ``resolved_links`` — a snapshot must record what was authored, and
    resolution is rebuildable. Body whitespace is collapsed exactly as
    ``build._hash_payload`` does, so reflowing prose is not an edit.
    """
    return {
        "history_format": HISTORY_FORMAT,
        "type": item.type,
        "fields": item.fields,
        "links": item.links,
        "body": _collapse_ws(item.body),
    }


def digest_of(payload: dict[str, object]) -> str:
    """sha256 over the canonical JSON of a semantic payload.

    ``sort_keys=True`` makes declaration order irrelevant; ``default=str``
    mirrors ``build._hash_blob`` so an exotic parsed value serializes
    deterministically instead of raising. Full 64-hex digest: object filenames
    are content addresses and collision margin is free here.
    """
    blob = json.dumps(payload, sort_keys=True, default=str)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


def semantic_digest(item: Item) -> str:
    """The separately versioned history digest of ``item``. Not
    ``item.content_hash`` (see the module docstring) and unaffected by
    ``build.HASH_FORMAT``."""
    return digest_of(semantic_payload(item))


# ------------------------------------------------------------ object records


def object_payload(item: Item) -> dict[str, object]:
    """The full object-file payload: the semantic core plus identity and
    provenance, which are stored but excluded from the digest."""
    payload = dict(semantic_payload(item))
    payload["key"] = item.key
    payload["id"] = item.id
    payload["source"] = {"file": item.source_file, "line": item.source_line}
    return payload


def _format_yaml(payload: dict[str, object], header: str) -> str:
    return header + yaml.safe_dump(
        payload, sort_keys=True, default_flow_style=False, allow_unicode=True
    )


def objects_dir(root: str) -> str:
    return os.path.join(str(root), OBJECTS_DIR)


def events_dir(root: str) -> str:
    return os.path.join(str(root), EVENTS_DIR)


def object_path(root: str, digest: str) -> str:
    return os.path.join(objects_dir(root), f"{digest}.yaml")


def save_object(root: str, item: Item) -> tuple[str, str]:
    """Write ``item``'s snapshot; return ``(digest, path)``.

    Content-addressed, so the write is idempotent: a second save of the same
    state finds the file already there and writes nothing. ``source`` is
    per-capture provenance, not content — two captures of one state from
    different files/lines share a digest, and the first capture's provenance
    stands. What raises is an existing file whose *semantic core* does not
    hash to the digest in its filename: a content address that doesn't
    address its content is corruption, and it is never overwritten.
    """
    digest = semantic_digest(item)
    path = object_path(root, digest)
    text = _format_yaml(object_payload(item), _OBJECT_HEADER)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fh:
            existing = yaml_safe_load(fh)
        _check_format(existing, path)
        core = {
            k: existing[k]
            for k in ("history_format", "type", "fields", "links", "body")
            if k in existing
        }
        if digest_of(core) != digest:
            raise HistoryError(
                f"history object {path} does not hash to the content address "
                "in its filename; refusing to overwrite it"
            )
        return digest, path
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return digest, path


def _check_format(data: object, where: str) -> None:
    if not isinstance(data, dict):
        raise HistoryError(f"{where}: expected a YAML mapping, got {type(data).__name__}")
    raw = data.get("history_format")
    if raw is None:
        raise HistoryError(f"{where}: missing history_format")
    try:
        version = int(raw)
    except (TypeError, ValueError):
        raise HistoryError(f"{where}: history_format {raw!r} is not an integer") from None
    if version > HISTORY_FORMAT:
        raise HistoryError(
            f"{where}: history_format {version} is newer than this build's "
            f"{HISTORY_FORMAT}; refusing to guess at a future format"
        )
    if version < 1:
        raise HistoryError(f"{where}: history_format {version} is not a real version")


def load_object(root: str, digest: str) -> dict[str, object]:
    """Load one object by its semantic digest, validating format and that the
    stored payload still hashes to the filename it lives under."""
    path = object_path(root, digest)
    if not os.path.isfile(path):
        raise HistoryError(f"no history object {digest} at {path}")
    with open(path, "r", encoding="utf-8") as fh:
        data = yaml_safe_load(fh)
    _check_format(data, path)
    data = dict(data)
    core = {k: data[k] for k in ("history_format", "type", "fields", "links", "body") if k in data}
    missing = {"history_format", "type", "fields", "links", "body"} - set(core)
    if missing:
        raise HistoryError(f"{path}: missing required key(s): {', '.join(sorted(missing))}")
    if digest_of(core) != digest:
        raise HistoryError(
            f"{path}: stored payload does not hash to its filename; the object has been tampered with"
        )
    return data


# ------------------------------------------------------------- event records


def event_id(kind: str, item_key: str, successor_key: str = "") -> str:
    """The derived id of an event: uuid5 over (kind, item_key, successor_key).

    Derived, not random (plan §H1): a replay of the same edge — the old-branch
    checkout case — regenerates the identical path and is a filesystem no-op.
    ``occurred_at`` is deliberately *not* an input; it is display metadata.
    """
    if not kind:
        raise HistoryError("event id requires a kind")
    if not item_key:
        raise HistoryError("event id requires an item_key")
    name = "\0".join([kind, item_key, successor_key or ""])
    return str(uuid.uuid5(_EVENT_NAMESPACE, name))


def append_event(
    root: str,
    kind: str,
    item_key: str,
    object_digest: str,
    *,
    successor_key: str = "",
    reason: str = "",
    occurred_at: object = None,
) -> str:
    """Append one event, idempotently; return its path.

    One event per (kind, item_key, successor_key) pair, enforced by the
    derived id: re-appending the same edge writes nothing new, even with a
    different ``occurred_at`` (a replay carries the replay clock, §2). If the
    file already exists but promises a *different* snapshot, that is two
    captures of one edge disagreeing about what was captured — a loud error,
    never a silent first-write-wins.
    """
    if kind not in EVENT_KINDS:
        raise HistoryError(f"unknown history event kind {kind!r}")
    if not object_digest:
        raise HistoryError("an event must name the object digest it records")
    eid = event_id(kind, item_key, successor_key)
    path = os.path.join(events_dir(root), f"{eid}.yaml")
    payload: dict[str, object] = {
        "history_format": HISTORY_FORMAT,
        "id": eid,
        "kind": kind,
        "item_key": item_key,
        "object": object_digest,
    }
    if successor_key:
        payload["successor_key"] = successor_key
    if reason:
        payload["reason"] = reason
    if occurred_at is not None:
        payload["occurred_at"] = occurred_at
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fh:
            existing = yaml_safe_load(fh)
        if not isinstance(existing, dict):
            raise HistoryError(f"{path}: existing event is not a YAML mapping")
        _check_format(existing, path)
        if existing.get("object") != object_digest:
            raise HistoryError(
                f"{path}: this edge was already captured against object "
                f"{existing.get('object')!r}; refusing to re-point it at {object_digest!r}"
            )
        return path
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(_format_yaml(payload, _EVENT_HEADER))
    return path


def load_events(root: str) -> list[dict[str, object]]:
    """Every event in the store, sorted by derived id (never by occurred_at —
    display metadata is not an ordering).

    Loud by design: a malformed event, an unknown kind, an id that disagrees
    with its filename, or the same (kind, item_key, successor_key) edge under
    two ids (only possible if ids were ever random) each raise. A history
    store that silently skips a bad record teaches its readers to distrust it.
    """
    directory = events_dir(root)
    if not os.path.isdir(directory):
        return []
    events: list[dict[str, object]] = []
    seen: dict[tuple[str, str, str], str] = {}
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".yaml"):
            continue
        path = os.path.join(directory, name)
        with open(path, "r", encoding="utf-8") as fh:
            data = yaml_safe_load(fh)
        _check_format(data, path)
        for required in ("id", "kind", "item_key", "object"):
            if not data.get(required):
                raise HistoryError(f"{path}: missing required key {required!r}")
        if data["kind"] not in EVENT_KINDS:
            raise HistoryError(f"{path}: unknown event kind {data['kind']!r}")
        stem = name[: -len(".yaml")]
        if data["id"] != stem:
            raise HistoryError(
                f"{path}: event id {data['id']!r} does not match its filename; "
                "event files are named by their derived id"
            )
        edge = (str(data["kind"]), str(data["item_key"]), str(data.get("successor_key") or ""))
        if edge in seen:
            raise HistoryError(
                f"{path}: duplicate event for edge {edge!r}, already recorded by {seen[edge]}"
            )
        seen[edge] = path
        events.append(dict(data))
    events.sort(key=lambda event: str(event["id"]))
    return events


# ------------------------------------------------------- the capture call site


class FollowCapture(NamedTuple):
    """What one capture attempt did: the announcement line (``""`` when the
    edge was already captured, so the caller prints nothing on a no-op), the
    event's path, and exactly which files this call created — so a caller
    running a batch of captures can undo its own writes when the surrounding
    transaction fails (plan §H2: the frozen edge and its event are one unit)."""

    announcement: str
    event_path: str
    created_event: bool
    created_object: "str | None"


def _follows_target_key(target: object) -> "str | None":
    """The key half of a frozen follows target (``ID@key``, or a bare
    well-formed key for an id-less tip); None for anything unresolved."""
    text = str(target)
    if "@" in text:
        return text.partition("@")[2]
    return None


def capture_followed(
    root: str,
    predecessor: Item,
    successor: Item,
    *,
    current_predecessor_keys: "set[str] | None" = None,
) -> FollowCapture:
    """Turn one resolved (predecessor, successor) pair into a `followed`
    event holding the predecessor's snapshot (plan §H2: the one function the
    capture call site adds to this store).

    The plan's five cases, in one function:

    * **Idempotence** (case five): the derived id means re-capturing the same
      edge is a filesystem no-op that announces nothing.
    * **Typo corrected** (case one): when the successor's *current* frozen
      edges no longer include a predecessor this successor was previously
      captured against, the new event is `followed-corrected`, naming the
      superseded key in `reason`. The original event is never deleted or
      rewritten. A merge — two parents both still on the successor's edge
      list — is not a correction, so `current_predecessor_keys` must be the
      successor's full current edge set, not just this pair.
    * **Old-branch replay** (case four): derived ids plus the content-addressed
      object make the replay write the identical path with the identical
      bytes. `occurred_at` is deliberately **not** written here: a wall-clock
      stamp would give one fact different bytes in two checkouts, and §2
      makes it display metadata nobody may order or gate on. The explicit
      `history capture` command (H4) is the author moment that can carry a
      clock.

    Cases two (VS Code's save refresh) and three (CI) are the caller's:
    capture rides the freeze's `write` flag, so a writable load captures and
    `--no-write` never reaches this function.
    """
    if not predecessor.key or not successor.key:
        raise HistoryError(
            "a follows: capture is addressed by surrogate key, and "
            f"{predecessor.id or '?'} or {successor.id or '?'} has none"
        )
    if current_predecessor_keys is None:
        current_predecessor_keys = {
            key
            for key in map(_follows_target_key, successor.links.get("follows", []))
            if key
        }
    superseded = sorted(
        {
            str(event["item_key"])
            for event in load_events(root)
            if event.get("successor_key") == successor.key
            and event.get("kind") in ("followed", "followed-corrected")
            and str(event["item_key"]) not in current_predecessor_keys
        }
    )
    kind = "followed-corrected" if superseded else "followed"
    reason = (
        "supersedes the followed edge from " + ", ".join(superseded)
        if superseded
        else ""
    )

    digest = semantic_digest(predecessor)
    eid = event_id(kind, predecessor.key, successor.key)
    event_path = os.path.join(events_dir(root), f"{eid}.yaml")
    if os.path.exists(event_path):
        return FollowCapture("", event_path, False, None)

    object_file = object_path(root, digest)
    object_existed = os.path.exists(object_file)
    save_object(root, predecessor)
    try:
        append_event(
            root,
            kind,
            predecessor.key,
            digest,
            successor_key=successor.key,
            reason=reason,
        )
    except Exception:
        # An object no event points at is a leak the transaction should not
        # leave behind; content-addressed, so removing it can only undo this
        # call's own write (it did not exist a moment ago).
        if not object_existed and os.path.exists(object_file):
            os.remove(object_file)
        raise

    announcement = (
        f"captured {predecessor.id or predecessor.key}: "
        f"{successor.id or successor.key} now follows it"
    )
    if superseded:
        announcement += f" (corrects {', '.join(superseded)})"
    return FollowCapture(
        announcement, event_path, True, None if object_existed else object_file
    )
